import {
  AnalyticsUpIcon,
  ArrowDownLeft01Icon,
  ArrowUpRight01Icon,
  BankIcon,
  MoneySafeIcon,
  TradeDownIcon,
} from '@hugeicons/core-free-icons'
import type { IconSvgElement } from '@hugeicons/react'
import { accountTypeEnum, categoryTypeEnum, transactionTypeEnum } from '@/lib/db/schema'

export const CURRENCY_CODES = [
  'USD',
  'EUR',
  'GBP',
  'JPY',
  'AUD',
  'CAD',
  'CHF',
  'CNY',
  'SEK',
  'NZD',
] as const

export const ACCOUNT_TYPES = accountTypeEnum
export const ACCOUNT_TYPES_ICONS: Record<(typeof ACCOUNT_TYPES)[number], IconSvgElement> = {
  cash: BankIcon,
  investment: AnalyticsUpIcon,
  liability: TradeDownIcon,
  other_asset: MoneySafeIcon,
}

export const CATEGORY_TYPES = categoryTypeEnum
export const CATEGORY_TYPES_ICONS: Record<(typeof CATEGORY_TYPES)[number], IconSvgElement> = {
  inflow: ArrowUpRight01Icon,
  outflow: ArrowDownLeft01Icon,
}

export const TRANSACTIONS_TYPES = transactionTypeEnum
export const TRANSACTIONS_ICONS: Record<(typeof TRANSACTIONS_TYPES)[number], IconSvgElement> = {
  inflow: ArrowUpRight01Icon,
  outflow: ArrowDownLeft01Icon,
}
export const TRANSACTIONS_TYPE_LABELS: Record<(typeof TRANSACTIONS_TYPES)[number], string> = {
  inflow: 'Income',
  outflow: 'Expense',
}

// ========== Country Codes ==========

export const COUNTRY_CODES = [
  'AD',
  'AE',
  'AF',
  'AG',
  'AL',
  'AM',
  'AO',
  'AR',
  'AT',
  'AU',
  'AZ',
  'BA',
  'BB',
  'BD',
  'BE',
  'BF',
  'BG',
  'BH',
  'BI',
  'BJ',
  'BN',
  'BO',
  'BR',
  'BS',
  'BT',
  'BW',
  'BY',
  'BZ',
  'CA',
  'CD',
  'CF',
  'CG',
  'CH',
  'CI',
  'CL',
  'CM',
  'CN',
  'CO',
  'CR',
  'CU',
  'CV',
  'CY',
  'CZ',
  'DE',
  'DJ',
  'DK',
  'DM',
  'DO',
  'DZ',
  'EC',
  'EE',
  'EG',
  'ES',
  'ET',
  'FI',
  'FJ',
  'FR',
  'GA',
  'GB',
  'GD',
  'GE',
  'GH',
  'GM',
  'GN',
  'GQ',
  'GR',
  'GT',
  'GW',
  'GY',
  'HK',
  'HN',
  'HR',
  'HT',
  'HU',
  'ID',
  'IE',
  'IL',
  'IN',
  'IQ',
  'IR',
  'IS',
  'IT',
  'JM',
  'JO',
  'JP',
  'KE',
  'KG',
  'KH',
  'KI',
  'KM',
  'KN',
  'KP',
  'KR',
  'KW',
  'KZ',
  'LA',
  'LB',
  'LC',
  'LI',
  'LK',
  'LR',
  'LS',
  'LT',
  'LU',
  'LV',
  'LY',
  'MA',
  'MC',
  'MD',
  'ME',
  'MG',
  'MH',
  'MK',
  'ML',
  'MM',
  'MN',
  'MO',
  'MR',
  'MT',
  'MU',
  'MV',
  'MW',
  'MX',
  'MY',
  'MZ',
  'NA',
  'NE',
  'NG',
  'NI',
  'NL',
  'NO',
  'NP',
  'NR',
  'NZ',
  'OM',
  'PA',
  'PE',
  'PH',
  'PK',
  'PL',
  'PT',
  'PW',
  'PY',
  'QA',
  'RO',
  'RS',
  'RU',
  'RW',
  'SA',
  'SB',
  'SC',
  'SD',
  'SE',
  'SG',
  'SI',
  'SK',
  'SL',
  'SM',
  'SN',
  'SO',
  'SR',
  'SS',
  'ST',
  'SV',
  'SY',
  'SZ',
  'TD',
  'TG',
  'TH',
  'TJ',
  'TL',
  'TM',
  'TN',
  'TO',
  'TR',
  'TT',
  'TV',
  'TW',
  'TZ',
  'UA',
  'UG',
  'US',
  'UY',
  'UZ',
  'VC',
  'VE',
  'VN',
  'VU',
  'WS',
  'YE',
  'ZA',
  'ZM',
  'ZW',
] as const
export type TCountryCode = (typeof COUNTRY_CODES)[number]

export const COUNTRY_NAMES: Record<(typeof COUNTRY_CODES)[number], string> = {
  AD: 'Andorra',
  AE: 'United Arab Emirates',
  AF: 'Afghanistan',
  AG: 'Antigua and Barbuda',
  AL: 'Albania',
  AM: 'Armenia',
  AO: 'Angola',
  AR: 'Argentina',
  AT: 'Austria',
  AU: 'Australia',
  AZ: 'Azerbaijan',
  BA: 'Bosnia and Herzegovina',
  BB: 'Barbados',
  BD: 'Bangladesh',
  BE: 'Belgium',
  BF: 'Burkina Faso',
  BG: 'Bulgaria',
  BH: 'Bahrain',
  BI: 'Burundi',
  BJ: 'Benin',
  BN: 'Brunei',
  BO: 'Bolivia',
  BR: 'Brazil',
  BS: 'Bahamas',
  BT: 'Bhutan',
  BW: 'Botswana',
  BY: 'Belarus',
  BZ: 'Belize',
  CA: 'Canada',
  CD: 'Congo (DRC)',
  CF: 'Central African Republic',
  CG: 'Congo (Republic)',
  CH: 'Switzerland',
  CI: 'Ivory Coast',
  CL: 'Chile',
  CM: 'Cameroon',
  CN: 'China',
  CO: 'Colombia',
  CR: 'Costa Rica',
  CU: 'Cuba',
  CV: 'Cape Verde',
  CY: 'Cyprus',
  CZ: 'Czech Republic',
  DE: 'Germany',
  DJ: 'Djibouti',
  DK: 'Denmark',
  DM: 'Dominica',
  DO: 'Dominican Republic',
  DZ: 'Algeria',
  EC: 'Ecuador',
  EE: 'Estonia',
  EG: 'Egypt',
  ES: 'Spain',
  ET: 'Ethiopia',
  FI: 'Finland',
  FJ: 'Fiji',
  FR: 'France',
  GA: 'Gabon',
  GB: 'United Kingdom',
  GD: 'Grenada',
  GE: 'Georgia',
  GH: 'Ghana',
  GM: 'Gambia',
  GN: 'Guinea',
  GQ: 'Equatorial Guinea',
  GR: 'Greece',
  GT: 'Guatemala',
  GW: 'Guinea-Bissau',
  GY: 'Guyana',
  HK: 'Hong Kong',
  HN: 'Honduras',
  HR: 'Croatia',
  HT: 'Haiti',
  HU: 'Hungary',
  ID: 'Indonesia',
  IE: 'Ireland',
  IL: 'Israel',
  IN: 'India',
  IQ: 'Iraq',
  IR: 'Iran',
  IS: 'Iceland',
  IT: 'Italy',
  JM: 'Jamaica',
  JO: 'Jordan',
  JP: 'Japan',
  KE: 'Kenya',
  KG: 'Kyrgyzstan',
  KH: 'Cambodia',
  KI: 'Kiribati',
  KM: 'Comoros',
  KN: 'Saint Kitts and Nevis',
  KP: 'North Korea',
  KR: 'South Korea',
  KW: 'Kuwait',
  KZ: 'Kazakhstan',
  LA: 'Laos',
  LB: 'Lebanon',
  LC: 'Saint Lucia',
  LI: 'Liechtenstein',
  LK: 'Sri Lanka',
  LR: 'Liberia',
  LS: 'Lesotho',
  LT: 'Lithuania',
  LU: 'Luxembourg',
  LV: 'Latvia',
  LY: 'Libya',
  MA: 'Morocco',
  MC: 'Monaco',
  MD: 'Moldova',
  ME: 'Montenegro',
  MG: 'Madagascar',
  MH: 'Marshall Islands',
  MK: 'North Macedonia',
  ML: 'Mali',
  MM: 'Myanmar',
  MN: 'Mongolia',
  MO: 'Macau',
  MR: 'Mauritania',
  MT: 'Malta',
  MU: 'Mauritius',
  MV: 'Maldives',
  MW: 'Malawi',
  MX: 'Mexico',
  MY: 'Malaysia',
  MZ: 'Mozambique',
  NA: 'Namibia',
  NE: 'Niger',
  NG: 'Nigeria',
  NI: 'Nicaragua',
  NL: 'Netherlands',
  NO: 'Norway',
  NP: 'Nepal',
  NR: 'Nauru',
  NZ: 'New Zealand',
  OM: 'Oman',
  PA: 'Panama',
  PE: 'Peru',
  PH: 'Philippines',
  PK: 'Pakistan',
  PL: 'Poland',
  PT: 'Portugal',
  PW: 'Palau',
  PY: 'Paraguay',
  QA: 'Qatar',
  RO: 'Romania',
  RS: 'Serbia',
  RU: 'Russia',
  RW: 'Rwanda',
  SA: 'Saudi Arabia',
  SB: 'Solomon Islands',
  SC: 'Seychelles',
  SD: 'Sudan',
  SE: 'Sweden',
  SG: 'Singapore',
  SI: 'Slovenia',
  SK: 'Slovakia',
  SL: 'Sierra Leone',
  SM: 'San Marino',
  SN: 'Senegal',
  SO: 'Somalia',
  SR: 'Suriname',
  SS: 'South Sudan',
  ST: 'Sao Tome and Principe',
  SV: 'El Salvador',
  SY: 'Syria',
  SZ: 'Eswatini',
  TD: 'Chad',
  TG: 'Togo',
  TH: 'Thailand',
  TJ: 'Tajikistan',
  TL: 'Timor-Leste',
  TM: 'Turkmenistan',
  TN: 'Tunisia',
  TO: 'Tonga',
  TR: 'Turkey',
  TT: 'Trinidad and Tobago',
  TV: 'Tuvalu',
  TW: 'Taiwan',
  TZ: 'Tanzania',
  UA: 'Ukraine',
  UG: 'Uganda',
  US: 'United States',
  UY: 'Uruguay',
  UZ: 'Uzbekistan',
  VC: 'Saint Vincent and the Grenadines',
  VE: 'Venezuela',
  VN: 'Vietnam',
  VU: 'Vanuatu',
  WS: 'Samoa',
  YE: 'Yemen',
  ZA: 'South Africa',
  ZM: 'Zambia',
  ZW: 'Zimbabwe',
}

export const SORTED_COUNTRIES = COUNTRY_CODES.map((code) => ({
  code,
  name: COUNTRY_NAMES[code],
})).sort((a, b) => a.name.localeCompare(b.name))

// ========== Timezone Codes ==========

export const TIMEZONE_CODES = [
  'UTC',
  'Africa/Cairo',
  'Africa/Johannesburg',
  'Africa/Lagos',
  'America/Argentina/Buenos_Aires',
  'America/Bogota',
  'America/Chicago',
  'America/Denver',
  'America/Los_Angeles',
  'America/Mexico_City',
  'America/New_York',
  'America/Sao_Paulo',
  'America/Toronto',
  'Asia/Bangkok',
  'Asia/Dubai',
  'Asia/Hong_Kong',
  'Asia/Jakarta',
  'Asia/Jerusalem',
  'Asia/Seoul',
  'Asia/Shanghai',
  'Asia/Singapore',
  'Asia/Tokyo',
  'Australia/Sydney',
  'Europe/Amsterdam',
  'Europe/Berlin',
  'Europe/Brussels',
  'Europe/London',
  'Europe/Madrid',
  'Europe/Paris',
  'Europe/Rome',
  'Europe/Zurich',
  'Pacific/Auckland',
] as const

export const TIMEZONE_NAMES: Record<(typeof TIMEZONE_CODES)[number], string> = {
  UTC: 'Universal Coordinated Time',
  'Africa/Cairo': 'Cairo, Egypt',
  'Africa/Johannesburg': 'Johannesburg, South Africa',
  'Africa/Lagos': 'Lagos, Nigeria',
  'America/Argentina/Buenos_Aires': 'Buenos Aires, Argentina',
  'America/Bogota': 'Bogotá, Colombia',
  'America/Chicago': 'Chicago (Central Time)',
  'America/Denver': 'Denver (Mountain Time)',
  'America/Los_Angeles': 'Los Angeles (Pacific Time)',
  'America/Mexico_City': 'Mexico City, Mexico',
  'America/New_York': 'New York (Eastern Time)',
  'America/Sao_Paulo': 'São Paulo, Brazil',
  'America/Toronto': 'Toronto, Canada',
  'Asia/Bangkok': 'Bangkok, Thailand',
  'Asia/Dubai': 'Dubai, UAE',
  'Asia/Hong_Kong': 'Hong Kong, China',
  'Asia/Jakarta': 'Jakarta, Indonesia',
  'Asia/Jerusalem': 'Jerusalem, Israel',
  'Asia/Seoul': 'Seoul, South Korea',
  'Asia/Shanghai': 'Shanghai, China',
  'Asia/Singapore': 'Singapore',
  'Asia/Tokyo': 'Tokyo, Japan',
  'Australia/Sydney': 'Sydney, Australia',
  'Europe/Amsterdam': 'Amsterdam, Netherlands',
  'Europe/Berlin': 'Berlin, Germany',
  'Europe/Brussels': 'Brussels, Belgium',
  'Europe/London': 'London, UK',
  'Europe/Madrid': 'Madrid, Spain',
  'Europe/Paris': 'Paris, France',
  'Europe/Rome': 'Rome, Italy',
  'Europe/Zurich': 'Zurich, Switzerland',
  'Pacific/Auckland': 'Auckland, New Zealand',
}

export const SORTED_TIMEZONES = TIMEZONE_CODES.map((code) => ({
  code,
  name: TIMEZONE_NAMES[code],
})).sort((a, b) => a.name.localeCompare(b.name))

// ========== Date Format Codes ==========

export const DATE_FORMAT_CODES = [
  'DD/MM/YYYY',
  'MM/DD/YYYY',
  'YYYY-MM-DD',
  'DD.MM.YYYY',
  'MMM D, YYYY',
  'D MMM YYYY',
  'YYYY/MM/DD',
] as const

export type DateFormatCode = (typeof DATE_FORMAT_CODES)[number]

export const DATE_FORMAT_LABELS: Record<DateFormatCode, string> = {
  'DD/MM/YYYY': 'DD/MM/YYYY (28/12/2025)',
  'MM/DD/YYYY': 'MM/DD/YYYY (12/28/2025)',
  'YYYY-MM-DD': 'YYYY-MM-DD (2025-12-28)',
  'DD.MM.YYYY': 'DD.MM.YYYY (28.12.2025)',
  'MMM D, YYYY': 'MMM D, YYYY (Dec 28, 2025)',
  'D MMM YYYY': 'D MMM YYYY (28 Dec 2025)',
  'YYYY/MM/DD': 'YYYY/MM/DD (2025/12/28)',
}

export const DATE_FORMAT_OPTIONS = DATE_FORMAT_CODES.map((code) => ({
  code,
  label: DATE_FORMAT_LABELS[code],
}))
