/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TransactionsIndexRouteImport } from './routes/transactions/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as BudgetsIndexRouteImport } from './routes/budgets/index'
import { Route as AnalyticsIndexRouteImport } from './routes/analytics/index'
import { Route as AccountsIndexRouteImport } from './routes/accounts/index'
import { Route as TransactionsImportRouteImport } from './routes/transactions/import'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthLogoutRouteImport } from './routes/auth/logout'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as SettingsCategoriesImportRouteImport } from './routes/settings/categories/import'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsIndexRoute = TransactionsIndexRouteImport.update({
  id: '/transactions/',
  path: '/transactions/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetsIndexRoute = BudgetsIndexRouteImport.update({
  id: '/budgets/',
  path: '/budgets/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsIndexRoute = AnalyticsIndexRouteImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsIndexRoute = AccountsIndexRouteImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsImportRoute = TransactionsImportRouteImport.update({
  id: '/transactions/import',
  path: '/transactions/import',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/auth/logout',
  path: '/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsCategoriesImportRoute =
  SettingsCategoriesImportRouteImport.update({
    id: '/settings/categories/import',
    path: '/settings/categories/import',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/transactions/import': typeof TransactionsImportRoute
  '/accounts': typeof AccountsIndexRoute
  '/analytics': typeof AnalyticsIndexRoute
  '/budgets': typeof BudgetsIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/transactions': typeof TransactionsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/settings/categories/import': typeof SettingsCategoriesImportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/transactions/import': typeof TransactionsImportRoute
  '/accounts': typeof AccountsIndexRoute
  '/analytics': typeof AnalyticsIndexRoute
  '/budgets': typeof BudgetsIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/transactions': typeof TransactionsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/settings/categories/import': typeof SettingsCategoriesImportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/transactions/import': typeof TransactionsImportRoute
  '/accounts/': typeof AccountsIndexRoute
  '/analytics/': typeof AnalyticsIndexRoute
  '/budgets/': typeof BudgetsIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/transactions/': typeof TransactionsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/settings/categories/import': typeof SettingsCategoriesImportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/health'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/transactions/import'
    | '/accounts'
    | '/analytics'
    | '/budgets'
    | '/profile'
    | '/settings'
    | '/transactions'
    | '/api/auth/$'
    | '/settings/categories/import'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/health'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/transactions/import'
    | '/accounts'
    | '/analytics'
    | '/budgets'
    | '/profile'
    | '/settings'
    | '/transactions'
    | '/api/auth/$'
    | '/settings/categories/import'
  id:
    | '__root__'
    | '/'
    | '/api/health'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/transactions/import'
    | '/accounts/'
    | '/analytics/'
    | '/budgets/'
    | '/profile/'
    | '/settings/'
    | '/transactions/'
    | '/api/auth/$'
    | '/settings/categories/import'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiHealthRoute: typeof ApiHealthRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
  TransactionsImportRoute: typeof TransactionsImportRoute
  AccountsIndexRoute: typeof AccountsIndexRoute
  AnalyticsIndexRoute: typeof AnalyticsIndexRoute
  BudgetsIndexRoute: typeof BudgetsIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  TransactionsIndexRoute: typeof TransactionsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  SettingsCategoriesImportRoute: typeof SettingsCategoriesImportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/': {
      id: '/transactions/'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budgets/': {
      id: '/budgets/'
      path: '/budgets'
      fullPath: '/budgets'
      preLoaderRoute: typeof BudgetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/': {
      id: '/analytics/'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/': {
      id: '/accounts/'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/import': {
      id: '/transactions/import'
      path: '/transactions/import'
      fullPath: '/transactions/import'
      preLoaderRoute: typeof TransactionsImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/categories/import': {
      id: '/settings/categories/import'
      path: '/settings/categories/import'
      fullPath: '/settings/categories/import'
      preLoaderRoute: typeof SettingsCategoriesImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiHealthRoute: ApiHealthRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
  TransactionsImportRoute: TransactionsImportRoute,
  AccountsIndexRoute: AccountsIndexRoute,
  AnalyticsIndexRoute: AnalyticsIndexRoute,
  BudgetsIndexRoute: BudgetsIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  TransactionsIndexRoute: TransactionsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  SettingsCategoriesImportRoute: SettingsCategoriesImportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
